config/routes.rb
SimpleLineupManager::Application.routes.draw do
  get "welcome/index"
  resources :formats
  resources :statuses
  resources :themes
  resources :writers
  resources :editors
  resources :producers
  resources :stories

  root 'stories#index'

end

app/models/writer.rb
class Writer < ActiveRecord::Base
	has_many :stories
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_action :set_writer, only: [:show, :edit, :update, :destroy]

  # GET /writers
  # GET /writers.json
  def index
    @writers = Writer.all
  end

  # GET /writers/1
  # GET /writers/1.json
  def show
  end

  # GET /writers/new
  def new
    @writer = Writer.new
  end

  # GET /writers/1/edit
  def edit
  end

  # POST /writers
  # POST /writers.json
  def create
    @writer = Writer.new(writer_params)

    respond_to do |format|
      if @writer.save
        format.html { redirect_to @writer, notice: 'Writer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @writer }
      else
        format.html { render action: 'new' }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writers/1
  # PATCH/PUT /writers/1.json
  def update
    respond_to do |format|
      if @writer.update(writer_params)
        format.html { redirect_to @writer, notice: 'Writer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writers/1
  # DELETE /writers/1.json
  def destroy
    @writer.destroy
    respond_to do |format|
      format.html { redirect_to writers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writer
      @writer = Writer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def writer_params
      params.require(:writer).permit(:username, :email)
    end
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/writers/_form.html.erb
<%= form_for(@writer) do |f| %>
  <% if @writer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@writer.errors.count, "error") %> prohibited this writer from being saved:</h2>

      <ul>
      <% @writer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/writers/edit.html.erb
<h1>Editing writer</h1>

<%= render 'form' %>

app/views/writers/index.html.erb
<h1>Listing writers</h1>

<table>
  <thead>
    <tr>
      <th><%= sortable_column "Username" %></th>
      <th><%= sortable_column "Email" %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @writers.each do |writer| %>
      <tr>
        <td><%= writer.username %></td>
        <td><%= writer.email %></td>
        <td><%= link_to 'Show', writer %></td>
        <td><%= link_to 'Edit', edit_writer_path(writer) %></td>
        <td><%= link_to 'Destroy', writer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
    <%= link_to "New Writer", new_writer_path(@writer), {:class => "btn btn-default btn-lg"}  %> | 
    <%= link_to "Back to Stories", stories_path(@story), {:class => "btn btn-default btn-lg", :target => "_parent"}  %>
</div>

app/views/writers/new.html.erb
<h1>New writer</h1>

<%= render 'form' %>

app/views/writers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @writer.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @writer.email %>
</p>

<div>
    <%= link_to "Edit", edit_writer_path(@writer), {:class => "btn btn-default btn-lg"}  %> | 
    <%= link_to "Back to Writers", writers_path(@writer), {:class => "btn btn-default btn-lg", :target => "_parent"}  %> | 

    <%= link_to "Back to Stories", stories_path(@story), {:class => "btn btn-default btn-lg", :target => "_parent"}  %>
</div>