config/routes.rb
SimpleLineupManager::Application.routes.draw do
  get "welcome/index"
  resources :formats
  resources :statuses
  resources :themes
  resources :writers
  resources :editors
  resources :producers
  resources :stories

  root 'stories#index'

end

app/models/editor.rb
class Editor < ActiveRecord::Base
	has_many :stories
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  before_action :set_editor, only: [:show, :edit, :update, :destroy]

  # GET /editors
  # GET /editors.json
  def index
    @editors = Editor.all
  end

  # GET /editors/1
  # GET /editors/1.json
  def show
  end

  # GET /editors/new
  def new
    @editor = Editor.new
  end

  # GET /editors/1/edit
  def edit
  end

  # POST /editors
  # POST /editors.json
  def create
    @editor = Editor.new(editor_params)

    respond_to do |format|
      if @editor.save
        format.html { redirect_to @editor, notice: 'Editor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @editor }
      else
        format.html { render action: 'new' }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editors/1
  # PATCH/PUT /editors/1.json
  def update
    respond_to do |format|
      if @editor.update(editor_params)
        format.html { redirect_to @editor, notice: 'Editor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @editor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editors/1
  # DELETE /editors/1.json
  def destroy
    @editor.destroy
    respond_to do |format|
      format.html { redirect_to editors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editor
      @editor = Editor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def editor_params
      params.require(:editor).permit(:username, :email)
    end
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/views/editors/_form.html.erb
<%= form_for(@editor) do |f| %>
  <% if @editor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@editor.errors.count, "error") %> prohibited this editor from being saved:</h2>

      <ul>
      <% @editor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editors/edit.html.erb
<h1>Editing editor</h1>

<%= render 'form' %>

app/views/editors/index.html.erb
<h1>Listing editors</h1>

<table>
  <thead>
    <tr>
      <th><%= sortable_column "Username" %></th>
      <th><%= sortable_column "Email" %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @editors.each do |editor| %>
      <tr>
        <td><%= editor.username %></td>
        <td><%= editor.email %></td>
        <td><%= link_to 'Show', editor %></td>
        <td><%= link_to 'Edit', edit_editor_path(editor) %></td>
        <td><%= link_to 'Destroy', editor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<div>
    <%= link_to "New Editor", new_editor_path(@editor), {:class => "btn btn-default btn-lg"}  %> | 
    <%= link_to "Back to Stories", stories_path(@story), {:class => "btn btn-default btn-lg", :target => "_parent"}  %>
</div>

app/views/editors/new.html.erb
<h1>New editor</h1>

<%= render 'form' %>

app/views/editors/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @editor.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @editor.email %>
</p>

<div>
    <%= link_to "Edit", edit_editor_path(@editor), {:class => "btn btn-default btn-lg"}  %> | 
    <%= link_to "Back to Editors", editors_path(@editor), {:class => "btn btn-default btn-lg", :target => "_parent"}  %> | 

    <%= link_to "Back to Stories", stories_path(@story), {:class => "btn btn-default btn-lg", :target => "_parent"}  %>
</div>