config/routes.rb
SimpleLineupManager::Application.routes.draw do
  get "welcome/index"
  resources :formats
  resources :statuses
  resources :themes
  resources :writers
  resources :editors
  resources :producers
  resources :stories

  root 'stories#index'

end

app/models/producer.rb
class Producer < ActiveRecord::Base
	has_many :stories
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
    handles_sortable_columns
    before_action :set_producer, only: [:show, :edit, :update, :destroy]

  # GET /producers
  # GET /producers.json
  def index
    order = sortable_column_order
    @producers = Producer.order(order)
  end


  # GET /producers/1
  # GET /producers/1.json
  def show
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit
  end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(producer_params)

    respond_to do |format|
      if @producer.save
        format.html { redirect_to @producer, notice: 'Producer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @producer }
      else
        format.html { render action: 'new' }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producers/1
  # PATCH/PUT /producers/1.json
  def update
    respond_to do |format|
      if @producer.update(producer_params)
        format.html { redirect_to @producer, notice: 'Producer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer.destroy
    respond_to do |format|
      format.html { redirect_to producers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producer
      @producer = Producer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producer_params
      params.require(:producer).permit(:username, :email)
    end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.erb
<%= form_for(@producer) do |f| %>
  <% if @producer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producer.errors.count, "error") %> prohibited this producer from being saved:</h2>

      <ul>
      <% @producer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/producers/edit.html.erb
<h1>Editing producer</h1>

<%= render 'form' %>

app/views/producers/index.html.erb
<h1>Listing producers</h1>

<table>
  <thead>
    <tr>
      <th><%= sortable_column "Username" %></th>
      <th><%= sortable_column "Email" %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @producers.each do |producer| %>
      <tr>
        <td><%= producer.username %></td>
        <td><%= producer.email %></td>
        <td><%= link_to 'Show', producer %></td>
        <td><%= link_to 'Edit', edit_producer_path(producer) %></td>
        <td><%= link_to 'Destroy', producer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
    <%= link_to "New Producer", new_producer_path(@producer), {:class => "btn btn-default btn-lg"}  %> | 
    <%= link_to "Back to Stories", stories_path(@story), {:class => "btn btn-default btn-lg", :target => "_parent"}  %>
</div>

app/views/producers/new.html.erb
<h1>New producer</h1>

<%= render 'form' %>

app/views/producers/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @producer.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @producer.email %>
</p>

<div>
    <%= link_to "Edit", edit_producer_path(@producer), {:class => "btn btn-default btn-lg"}  %> | 
    <%= link_to "Back to Producers", producers_path(@producers), {:class => "btn btn-default btn-lg", :target => "_parent"}  %> | 

    <%= link_to "Back to Stories", stories_path(@story), {:class => "btn btn-default btn-lg", :target => "_parent"}  %>
</div>